[template]
cargo_generate_version = ">=0.18.0"

[placeholders.target]
prompt = "Choose a target"
choices = [
    "esp32",
    "esp32c2",
    "esp32c3",
    "esp32c5",
    "esp32c6",
    "esp32c61",
    "esp32h2",
    "esp32s2",
    "esp32s3",
]
default = "esp32"
type = "string"

[placeholders.template]
prompt = "Choose a template"
choices = [
    "Blinky",
    "GPIO In/Out",
    "LEDC (PWM)",
    "MCPWM (Motor Control PWM)",
    "UART Echo",
    "I2C SSD1306",
    "I2C SSD1306 + DS3231",
    "Wi-Fi Scan",
    "Wi-Fi HTTP Client"
]
default = "Blinky"
type = "string"

[conditional.'template != "Wi-Fi HTTP Client"']
ignore = ["src/private_info.rs"]
